In [1]:
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_digits

digits = load_digits()

In [2]:
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size = 0.3)

In [4]:
ss = X_train, X_test, y_train, y_test

In [5]:
lr = LogisticRegression()
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

C:\Users\prana\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9666666666666667

In [6]:
svm = SVC()
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.9833333333333333

In [7]:
RF =  RandomForestClassifier()
RF.fit(X_train, y_train)
RF.score(X_test, y_test)

0.975925925925926

In [8]:
from sklearn.model_selection import KFold
kf = KFold(n_splits = 3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [9]:
def getscore(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [10]:
getscore(RF, X_train, X_test, y_train, y_test )

0.9703703703703703

In [11]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9,10]):
    print(train_index, test_index)

[4 5 6 7 8 9] [0 1 2 3]
[0 1 2 3 7 8 9] [4 5 6]
[0 1 2 3 4 5 6] [7 8 9]


In [12]:
from sklearn.model_selection import StratifiedKFold
skf = StratifiedKFold(n_splits = 3)
skf

StratifiedKFold(n_splits=3, random_state=None, shuffle=False)

In [13]:
scoreL = []
scoreS = []
scoreR = []

for train_index, test_index in kf.split(digits.data):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
    digits.target[train_index], digits.target[test_index]

    
    scoreS.append(getscore(svm,X_train, X_test, y_train, y_test ))
    scoreR.append(getscore(RF,X_train, X_test, y_train, y_test ))

In [14]:
print(scoreS)

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]


In [15]:
print(scoreR)

[0.9398998330550918, 0.9582637729549248, 0.9215358931552587]


In [16]:
from sklearn.model_selection import cross_val_score

cs = cross_val_score

In [17]:
cs(svm , digits.data, digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [18]:
cs(RF , digits.data, digits.target)

array([0.93611111, 0.89444444, 0.95543175, 0.9637883 , 0.93314763])