In [51]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from word2number import w2n
import sklearn

In [52]:
df = pd.read_csv('hiring.csv')
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [53]:
s = df['test_score(out of 10)'].median()

In [54]:
df['test_score(out of 10)'].fillna(s , inplace = True)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    8.0                           7      72000
7     eleven                    7.0                           8      80000

In [55]:
def convert_words_to_numbers(word):
    try:
        return w2n.word_to_num(word)
    except ValueError:
        # Handle the case where the word cannot be converted to a number
        return word
    
df['experience'] = df['experience'].apply(convert_words_to_numbers)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0         NaN                    8.0                           9      50000
1         NaN                    8.0                           6      45000
2         5.0                    6.0                           7      60000
3         2.0                   10.0                          10      65000
4         7.0                    9.0                           6      70000
5         3.0                    7.0                          10      62000
6        10.0                    8.0                           7      72000
7        11.0                    7.0                           8      80000

In [56]:
r = df.experience.median()
r

6.0

In [57]:
df.experience.fillna(0, inplace = True)

In [58]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0         0.0                    8.0                           9      50000
1         0.0                    8.0                           6      45000
2         5.0                    6.0                           7      60000
3         2.0                   10.0                          10      65000
4         7.0                    9.0                           6      70000
5         3.0                    7.0                          10      62000
6        10.0                    8.0                           7      72000
7        11.0                    7.0                           8      80000

In [59]:
import math
median_val = math.floor(df['experience'].median() )
df[['experience','test_score(out of 10)']] = df[['experience','test_score(out of 10)']].astype(int)

In [60]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                      8                           9      50000
1           0                      8                           6      45000
2           5                      6                           7      60000
3           2                     10                          10      65000
4           7                      9                           6      70000
5           3                      7                          10      62000
6          10                      8                           7      72000
7          11                      7                           8      80000

In [61]:
reg = linear_model.LinearRegression()
reg.fit(df[['experience','test_score(out of 10)','interview_score(out of 10)']], df['salary($)'])

LinearRegression()

In [62]:
reg.predict([[2,10,10]])

C:\Users\prana\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([63872.63464338])

In [63]:
reg.predict([[12,10,10]])

C:\Users\prana\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([92002.18340611])

In [64]:
import pickle

In [65]:
with open('model_pickle', 'wb') as f:
    pickle.dump(reg, f)

In [66]:
with open('model_pickle', 'rb') as f:
    mp = pickle.load(f)

In [67]:
mp.predict([[12,10,7]])

C:\Users\prana\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([85386.4628821])

In [68]:
import inspect
inspect.getfile(inspect.currentframe())

'C:\\Users\\prana\\AppData\\Local\\Temp\\ipykernel_25460\\3653608800.py'

In [70]:
pip install joblib

Note: you may need to restart the kernel to use updated packages.


In [71]:
joblib.dump(reg, 'model1')

['model1']

In [73]:
mk = joblib.load('model1')

In [74]:
mk.predict([[12,10,10,]])

C:\Users\prana\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([92002.18340611])

In [76]:
reg.score(df[['experience','test_score(out of 10)','interview_score(out of 10)']], df['salary($)'])

0.961678000257796