In [1]:
import numpy as np

In [12]:
a = np.array([[1,2],[3,2],[4,8],[5,2],[6,2]])
a.ndim      # no. of dimensions
a.itemsize  # integer so 4 (size of the data type)

4

In [13]:
a.dtype

dtype('int32')

In [16]:
b =  np.array([[1,2],[3,2],[4,8]], dtype = np.float64)
b.dtype

dtype('float64')

In [18]:
b.size

6

In [19]:
b.shape   # no.of rows and columns

(3, 2)

In [21]:
s = np.zeros([3,2])   
s

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [26]:
j = np.ones([2,3])
j

array([[1., 1., 1.],
       [1., 1., 1.]])

In [39]:
e = np.arange(1,6)
e

array([1, 2, 3, 4, 5])

In [43]:
f = np.linspace(1,5,10)
print(f)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [47]:
# to convert a multi dimensional array into a single flat array
x = a.ravel()
print(x)

[1 2 3 2 4 8 5 2 6 2]
